### ISSUE TITLE
QA chain

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#20] opened 2016-04-21 16:37 UTC
We need a system/process to test changes that conforms to best practices for open-sourced web apps.

**Comment by rjkroege** [comment] 2016-05-03 14:20
Before we've released the first milestone, we should probably have a weekly bug bash on Wednesdays? After we've released, we need the "released" version and the "testing" version and deploy testing versions to release after collective happiness on Wednesday evenings?

I'm presuming in this though that we have some kind of automatic regression test as part of the build system. Regression tests seem relatively easy (well, someone has to write them but that's just part for the course) for the backend code. Browser testing frameworks seems tedious? I'm hoping that we can have some kind of JS test framework running in node against a fake DOM.

**Comment by techieshark** [comment] 2017-03-30 20:33
Since we're using Travis CI to test all pull requests, and there's an open issue for JS testing (#109), I'd propose we close this issue while possibly opening another issue describing any specific testing gaps we want to fill. Thoughts?

**Closed** 2017-03-30 20:40 UTC
Labels: tooling
